In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import numpy as np
import pandas as pd
from pathlib import Path
from collections import Counter

In [3]:
from sklearn.metrics import balanced_accuracy_score
from sklearn.metrics import confusion_matrix
from imblearn.metrics import classification_report_imbalanced

# Read the CSV and Perform Basic Data Cleaning

In [4]:
# https://help.lendingclub.com/hc/en-us/articles/215488038-What-do-the-different-Note-statuses-mean-

columns = [
    "loan_amnt", "int_rate", "installment", "home_ownership",
    "annual_inc", "verification_status", "issue_d", "loan_status",
    "pymnt_plan", "dti", "delinq_2yrs", "inq_last_6mths",
    "open_acc", "pub_rec", "revol_bal", "total_acc",
    "initial_list_status", "out_prncp", "out_prncp_inv", "total_pymnt",
    "total_pymnt_inv", "total_rec_prncp", "total_rec_int", "total_rec_late_fee",
    "recoveries", "collection_recovery_fee", "last_pymnt_amnt", "next_pymnt_d",
    "collections_12_mths_ex_med", "policy_code", "application_type", "acc_now_delinq",
    "tot_coll_amt", "tot_cur_bal", "open_acc_6m", "open_act_il",
    "open_il_12m", "open_il_24m", "mths_since_rcnt_il", "total_bal_il",
    "il_util", "open_rv_12m", "open_rv_24m", "max_bal_bc",
    "all_util", "total_rev_hi_lim", "inq_fi", "total_cu_tl",
    "inq_last_12m", "acc_open_past_24mths", "avg_cur_bal", "bc_open_to_buy",
    "bc_util", "chargeoff_within_12_mths", "delinq_amnt", "mo_sin_old_il_acct",
    "mo_sin_old_rev_tl_op", "mo_sin_rcnt_rev_tl_op", "mo_sin_rcnt_tl", "mort_acc",
    "mths_since_recent_bc", "mths_since_recent_inq", "num_accts_ever_120_pd", "num_actv_bc_tl",
    "num_actv_rev_tl", "num_bc_sats", "num_bc_tl", "num_il_tl",
    "num_op_rev_tl", "num_rev_accts", "num_rev_tl_bal_gt_0",
    "num_sats", "num_tl_120dpd_2m", "num_tl_30dpd", "num_tl_90g_dpd_24m",
    "num_tl_op_past_12m", "pct_tl_nvr_dlq", "percent_bc_gt_75", "pub_rec_bankruptcies",
    "tax_liens", "tot_hi_cred_lim", "total_bal_ex_mort", "total_bc_limit",
    "total_il_high_credit_limit", "hardship_flag", "debt_settlement_flag"
]

target = ["loan_status"]

In [5]:
# Load the data
file_path = Path('LoanStats_2019Q1.csv')
df = pd.read_csv(file_path, skiprows=1)[:-2]
df = df.loc[:, columns].copy()

# Drop the null columns where all values are null
df = df.dropna(axis='columns', how='all')

# Drop the null rows
df = df.dropna()

# Remove the `Issued` loan status
issued_mask = df['loan_status'] != 'Issued'
df = df.loc[issued_mask]

# convert interest rate to numerical
df['int_rate'] = df['int_rate'].str.replace('%', '')
df['int_rate'] = df['int_rate'].astype('float') / 100


# Convert the target column values to low_risk and high_risk based on their values
x = {'Current': 'low_risk'}   
df = df.replace(x)

x = dict.fromkeys(['Late (31-120 days)', 'Late (16-30 days)', 'Default', 'In Grace Period'], 'high_risk')    
df = df.replace(x)

df.reset_index(inplace=True, drop=True)

df.head()

,loan_amnt,int_rate,installment,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,dti,...,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,hardship_flag,debt_settlement_flag
0,10500.0,0.1719,375.35,RENT,66000.0,Source Verified,Mar-2019,low_risk,n,27.24,...,85.7,100.0,0.0,0.0,65687.0,38199.0,2000.0,61987.0,N,N
1,25000.0,0.2000,929.09,MORTGAGE,105000.0,Verified,Mar-2019,low_risk,n,20.23,...,91.2,50.0,1.0,0.0,271427.0,60641.0,41200.0,49197.0,N,N
2,20000.0,0.2000,529.88,MORTGAGE,56000.0,Verified,Mar-2019,low_risk,n,24.26,...,66.7,50.0,0.0,0.0,60644.0,45684.0,7500.0,43144.0,N,N
3,10000.0,0.1640,353.55,RENT,92000.0,Verified,Mar-2019,low_risk,n,31.44,...,100.0,50.0,1.0,0.0,99506.0,68784.0,19700.0,76506.0,N,N
4,22000.0,0.1474,520.39,MORTGAGE,52000.0,Not Verified,Mar-2019,low_risk,n,18.76,...,100.0,0.0,0.0,0.0,219750.0,25919.0,27600.0,20000.0,N,N

# Split the Data into Training and Testing

In [6]:
# Create our features
X = df.drop("loan_status", axis=1)
X = pd.get_dummies(X)

# Create our target
y = df["loan_status"]

In [7]:
X.describe()

,loan_amnt,int_rate,installment,annual_inc,dti,delinq_2yrs,inq_last_6mths,open_acc,pub_rec,revol_bal,...,issue_d_Mar-2019,pymnt_plan_n,initial_list_status_f,initial_list_status_w,next_pymnt_d_Apr-2019,next_pymnt_d_May-2019,application_type_Individual,application_type_Joint App,hardship_flag_N,debt_settlement_flag_N
count,68817.000000,68817.000000,68817.000000,6.881700e+04,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,...,68817.000000,68817.0,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.0,68817.0
mean,16677.594562,0.127718,480.652863,8.821371e+04,21.778153,0.217766,0.497697,12.587340,0.126030,17604.142828,...,0.177238,1.0,0.123879,0.876121,0.383161,0.616839,0.860340,0.139660,1.0,1.0
std,10277.348590,0.048130,288.062432,1.155800e+05,20.199244,0.718367,0.758122,6.022869,0.336797,21835.880400,...,0.381873,0.0,0.329446,0.329446,0.486161,0.486161,0.346637,0.346637,0.0,0.0
min,1000.000000,0.060000,30.890000,4.000000e+01,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000,...,0.000000,1.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.0,1.0
25%,9000.000000,0.088100,265.730000,5.000000e+04,13.890000,0.000000,0.000000,8.000000,0.000000,6293.000000,...,0.000000,1.0,0.000000,1.000000,0.000000,0.000000,1.000000,0.000000,1.0,1.0
50%,15000.000000,0.118000,404.560000,7.300000e+04,19.760000,0.000000,0.000000,11.000000,0.000000,12068.000000,...,0.000000,1.0,0.000000,1.000000,0.000000,1.000000,1.000000,0.000000,1.0,1.0
75%,24000.000000,0.155700,648.100000,1.040000e+05,26.660000,0.000000,1.000000,16.000000,0.000000,21735.000000,...,0.000000,1.0,0.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.0,1.0
max,40000.000000,0.308400,1676.230000,8.797500e+06,999.000000,18.000000,5.000000,72.000000,4.000000,587191.000000,...,1.000000,1.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.0,1.0

In [8]:
# Check the balance of our target values
y.value_counts()

low_risk     68470
high_risk      347
Name: loan_status, dtype: int64

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)
X_train.shape

(51612, 95)

# Ensemble Learners

In this section, you will compare two ensemble algorithms to determine which algorithm results in the best performance. You will train a Balanced Random Forest Classifier and an Easy Ensemble AdaBoost classifier . For each algorithm, be sure to complete the folliowing steps:

1. Train the model using the training data. 
2. Calculate the balanced accuracy score from sklearn.metrics.
3. Print the confusion matrix from sklearn.metrics.
4. Generate a classication report using the `imbalanced_classification_report` from imbalanced-learn.
5. For the Balanced Random Forest Classifier onely, print the feature importance sorted in descending order (most important feature to least important) along with the feature score

Note: Use a random state of 1 for each algorithm to ensure consistency between tests

### Balanced Random Forest Classifier

In [10]:
# Resample the training data with the BalancedRandomForestClassifier
from imblearn.ensemble import BalancedRandomForestClassifier

rf_model = BalancedRandomForestClassifier(n_estimators=500, random_state=1)

# Fitting the model
rf_model = rf_model.fit(X_train, y_train)

In [11]:
# Calculated the balanced accuracy score
from sklearn.metrics import accuracy_score
y_pred = rf_model.predict(X_test)
acc_score = accuracy_score(y_test, y_pred)
print(acc_score)

0.9013077593722755

In [12]:
# Display the confusion matrix
from sklearn.metrics import confusion_matrix, classification_report

matrix = confusion_matrix(y_test, y_pred)
cm_df = pd.DataFrame(
    matrix, index=["Actual High-Risk", "Actual Low-Risk"], columns=["Predicted High_Risk", "Prediceted Low_Risk"])
cm_df

                  Predicted High_Risk  Prediceted Low_Risk
Actual High-Risk                   65                   36
Actual Low-Risk                  1662                15442

In [13]:
# Print the imbalanced classification report
from imblearn.metrics import classification_report_imbalanced
print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

  high_risk       0.04      0.64      0.90      0.07      0.76      0.57       101
   low_risk       1.00      0.90      0.64      0.95      0.76      0.60     17104

avg / total       0.99      0.90      0.65      0.94      0.76      0.60     17205

In [14]:
# List the features sorted in descending order by feature importance
sorted(zip(rf_model.feature_importances_, X.columns), reverse=True)

[(0.06661463495120314, 'total_rec_prncp'),
 (0.06318721529567178, 'total_rec_int'),
 (0.06061788889673201, 'total_pymnt'),
 (0.05826808075239343, 'total_pymnt_inv'),
 (0.0517793455702452, 'last_pymnt_amnt'),
 (0.030814261825048914, 'int_rate'),
 (0.018223876144473468, 'issue_d_Jan-2019'),
 (0.01758748442537316, 'installment'),
 (0.01701350913498804, 'dti'),
 (0.01643946938793743, 'mo_sin_old_rev_tl_op'),
 (0.01638879681134762, 'mths_since_recent_inq'),
 (0.01598335431546418, 'max_bal_bc'),
 (0.01582245081932586, 'out_prncp'),
 (0.015375773559199038, 'issue_d_Mar-2019'),
 (0.015335352361938786, 'out_prncp_inv'),
 (0.015039951662678231, 'total_bal_ex_mort'),
 (0.014672217013232325, 'avg_cur_bal'),
 (0.014515194032758657, 'tot_hi_cred_lim'),
 (0.014340120491331286, 'revol_bal'),
 (0.014264818693198206, 'annual_inc'),
 (0.013938521774605056, 'all_util'),
 (0.013757719619549559, 'total_rev_hi_lim'),
 (0.013740413820085784, 'bc_util'),
 (0.013613755428855435, 'total_bc_limit'),
 (0.01354320917024013, 'mo_sin_old_il_acct'),
 (0.01329915892795408, 'tot_cur_bal'),
 (0.013237432209615487, 'bc_open_to_buy'),
 (0.0131435054133756, 'total_bal_il'),
 (0.01294102845181073, 'mths_since_rcnt_il'),
 (0.012544577587869072, 'il_util'),
 (0.012374080719326703, 'loan_amnt'),
 (0.011589099026255392, 'mths_since_recent_bc'),
 (0.01151332547838206, 'total_il_high_credit_limit'),
 (0.01112946023954866, 'total_acc'),
 (0.010760347708985592, 'mo_sin_rcnt_rev_tl_op'),
 (0.010502638989345113, 'inq_last_12m'),
 (0.010249492079549845, 'num_il_tl'),
 (0.010213250147373879, 'num_rev_accts'),
 (0.010022778159725954, 'pct_tl_nvr_dlq'),
 (0.009670972494776485, 'mo_sin_rcnt_tl'),
 (0.009221983421739398, 'num_bc_tl'),
 (0.00916222517791571, 'num_sats'),
 (0.008628207574469216, 'num_actv_rev_tl'),
 (0.008405628259358153, 'open_il_24m'),
 (0.008132132818009645, 'open_acc'),
 (0.008130141767267061, 'acc_open_past_24mths'),
 (0.008119755119503861, 'num_op_rev_tl'),
 (0.007704066950542759, 'num_rev_tl_bal_gt_0'),
 (0.007413118831816394, 'num_bc_sats'),
 (0.007281299761749884, 'inq_fi'),
 (0.007220056958308362, 'num_tl_op_past_12m'),
 (0.007164731506007521, 'total_rec_late_fee'),
 (0.007018368297580994, 'open_act_il'),
 (0.006955650835148484, 'open_acc_6m'),
 (0.006749861155336104, 'num_actv_bc_tl'),
 (0.006605675054081339, 'percent_bc_gt_75'),
 (0.0063994444116548, 'total_cu_tl'),
 (0.005937135289542915, 'open_rv_24m'),
 (0.005900752004182788, 'inq_last_6mths'),
 (0.005632814516365807, 'mort_acc'),
 (0.0050364788885488825, 'next_pymnt_d_Apr-2019'),
 (0.004852500903680203, 'open_il_12m'),
 (0.004739629130406909, 'issue_d_Feb-2019'),
 (0.004681638637513726, 'open_rv_12m'),
 (0.0045938431281300875, 'next_pymnt_d_May-2019'),
 (0.00453717228377832, 'tot_coll_amt'),
 (0.0031509142420106506, 'num_accts_ever_120_pd'),
 (0.003104913468157793, 'delinq_2yrs'),
 (0.0021690931618630156, 'verification_status_Not Verified'),
 (0.0021254149953636847, 'home_ownership_RENT'),
 (0.002043986061244079, 'application_type_Individual'),
 (0.0020339234397456227, 'verification_status_Verified'),
 (0.0019155075206537598, 'application_type_Joint App'),
 (0.0019055235792357435, 'home_ownership_MORTGAGE'),
 (0.0018237855925908127, 'home_ownership_OWN'),
 (0.0018090040784838923, 'verification_status_Source Verified'),
 (0.001719871418260266, 'pub_rec_bankruptcies'),
 (0.0016225727760811638, 'pub_rec'),
 (0.0013503680710984511, 'initial_list_status_w'),
 (0.0011870895424150524, 'initial_list_status_f'),
 (0.0008288701751648158, 'num_tl_90g_dpd_24m'),
 (0.0005304828922961909, 'collections_12_mths_ex_med'),
 (0.0002786112597078863, 'home_ownership_ANY'),
 (0.00010719145121639157, 'chargeoff_within_12_mths'),
 (0.0, 'tax_liens'),
 (0.0, 'recoveries'),
 (0.0, 'pymnt_plan_n'),
 (0.0, 'policy_code'),
 (0.0, 'num_tl_30dpd'),
 (0.0, 'num_tl_120dpd_2m'),
 (0.0, 'hardship_flag_N'),
 (0.0, 'delinq_amnt'),
 (0.0, 'debt_settlement_flag_N'),
 (0.0, 'collection_recovery_fee'),
 (0.0, 'acc_now_delinq')]

### Easy Ensemble AdaBoost Classifier

In [15]:
# Train the EasyEnsembleClassifier
from imblearn.ensemble import EasyEnsembleClassifier

eec = EasyEnsembleClassifier(n_estimators=100, random_state=1)
eec.fit(X_train, y_train)

EasyEnsembleClassifier(n_estimators=100, random_state=1)

In [16]:
# Calculated the balanced accuracy score
from sklearn.metrics import accuracy_score

acc_score2 = accuracy_score(y_test, y_pred)
print(acc_score2)

0.9013077593722755

In [17]:
# Display the confusion matrix
from sklearn.metrics import confusion_matrix, classification_report

cm_df = pd.DataFrame(
    matrix, index=["Actual High-Risk", "Actual Low-Risk"], columns=["Predicted High_Risk", "Prediceted Low_Risk"])
cm_df

                  Predicted High_Risk  Prediceted Low_Risk
Actual High-Risk                   65                   36
Actual Low-Risk                  1662                15442

In [18]:
# Print the imbalanced classification report
from imblearn.metrics import classification_report_imbalanced

print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

  high_risk       0.04      0.64      0.90      0.07      0.76      0.57       101
   low_risk       1.00      0.90      0.64      0.95      0.76      0.60     17104

avg / total       0.99      0.90      0.65      0.94      0.76      0.60     17205